### ISSUE TITLE
如何实现抽中名单即时显示在右边

### ISSUE THREAD

**Issue by cedarice** [kaysonli/lucky-ball#1]
亲，非常感谢你的这个代码！
请问如何实现抽中的名单能及时显示在右边，谢谢！

**Comment by kaysonli** [comment]
> 亲，非常感谢你的这个代码！
> 请问如何实现抽中的名单能及时显示在右边，谢谢！

这个简单，现在右边显示的是batchPlayers，换成result[this.currentAward]就行了，表示当前奖项的所有中奖人员。再把显示条件对应改下

**Comment by kaysonli** [comment]
> 亲，非常感谢你的这个代码！
> 请问如何实现抽中的名单能及时显示在右边，谢谢！

这个简单，把对应的显示条件去掉就行了。当初为了不显示，特意加上的。欢迎star

**Comment by cedarice** [comment]
> > 亲，非常感谢你的这个代码！
> > 请问如何实现抽中的名单能及时显示在右边，谢谢！
> 
> 这个简单，把对应的显示条件去掉就行了。当初为了不显示，特意加上的。欢迎star

非常感谢，已实现此功能
